const tags = [
  { tag: "Indie", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Action", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Adventure", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Casual", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Simulation", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Strategy", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "RPG", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Early Access", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Free to Play", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Singleplayer", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Violent", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Sports", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Massively Multiplayer", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Gore", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Racing", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Nudity", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Atmospheric", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Great Soundtrack", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "2D", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Puzzle", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Sexual Content", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Multiplayer", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Story Rich", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Anime", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Difficult", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Fantasy", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "VR", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Horror", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Funny", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Pixel Graphics", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Sci-fi", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "First-Person", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Shooter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Female Protagonist", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Open World", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Platformer", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Retro", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Family Friendly", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Co-op", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Utilities", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Arcade", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Survival", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "FPS", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Turn-Based", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Cute", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Design & Illustration", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Visual Novel", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Comedy", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Exploration", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Sandbox", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Replay Value", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Online Co-Op", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Relaxing", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Psychological Horror", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Movie", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Classic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Controller", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Masterpiece", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Point & Click", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Colorful", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Third Person", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Space", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Fast-Paced", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Local Multiplayer", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Mature", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Education", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Tactical", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Mystery", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Dark", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Physics", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Zombies", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Realistic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Memes", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Animation & Modeling", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Short", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Building", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Management", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Software", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Survival Horror", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Audio Production", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Action-Adventure", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Shoot 'Em Up", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Choices Matter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Web Publishing", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Local Co-Op", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Roguelike", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Side Scroller", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Party-Based RPG", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "War", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "RPGMaker", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Action RPG", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Crafting", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Top-Down", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Roguelite", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Puzzle Platformer", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Music", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Walking Simulator", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Historical", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Competitive", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "PvP", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Turn-Based Strategy", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "RTS", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Beautiful", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Bullet Hell", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Video Production", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Character Customization", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Minimalist", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "JRPG", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Dark Fantasy", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Old School", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Post-apocalyptic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Romance", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Dating Sim", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Stealth", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Fighting", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Hack and Slash", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Hidden Object", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Procedural Generation", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Addictive", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Stylized", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Cartoony", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Medieval", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Futuristic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Multiple Endings", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Dungeon Crawler", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Third-Person Shooter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Tower Defense", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Base Building", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Drama", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "4 Player Local", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Turn-Based Combat", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Resource Management", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Surreal", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Military", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Card Game", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Moddable", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Magic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Top-Down Shooter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Cyberpunk", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "3D", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Dark Humor", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "World War II", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Isometric", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Robots", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Experimental", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Economy", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Hand-drawn", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Driving", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Team-Based", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Soundtrack", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Blood", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Turn-Based Tactics", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "City Builder", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Beat 'em up", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Metroidvania", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "3D Platformer", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Episodic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Software Training", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Thriller", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "MMORPG", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Interactive Fiction", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "LGBTQ+", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Cartoon", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Choose Your Own Adventure", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Epic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Board Game", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Game Development", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Perma Death", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Detective", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Aliens", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Hentai", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Flight", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Action Roguelike", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Illuminati", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Text-Based", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Real-Time", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Cult Classic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Twin Stick Shooter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Destruction", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Mouse only", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Arena Shooter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Psychological", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Crime", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Logic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Parkour", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Loot", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "PvE", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Level Editor", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "1990's", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "2.5D", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "NSFW", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Dark Comedy", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Abstract", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "2D Platformer", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Automobile Sim", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "1980s", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Demons", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Grand Strategy", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Real-Time with Pause", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Dystopian", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Lovecraftian", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Match 3", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Rhythm", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Alternate History", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Clicker", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Split Screen", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "2D Fighter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Score Attack", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Linear", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Space Sim", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Kickstarter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Wargame", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Steampunk", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Photo Editing", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Real Time Tactics", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "MOBA", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Strategy RPG", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Narration", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Science", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "GameMaker", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Tactical RPG", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Emotional", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Souls-like", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Battle Royale", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Tanks", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Political", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Psychedelic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Mechs", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Experience", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Lore-Rich", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Trains", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Documentary", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Time Management", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Touch-Friendly", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Remake", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Mod", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Co-op Campaign", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "4X", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Runner", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Swordplay", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Character Action Game", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Supernatural", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "3D Vision", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Dragons", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Ninja", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Voxel", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Inventory Management", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "eSports", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Pirates", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Cold War", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Politics", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Dinosaurs", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Otome", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Dungeons & Dragons", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Open World Survival Craft", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Superhero", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Comic Book", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Tutorial", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "CRPG", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Modern", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Nature", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Hacking", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Naval", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Cinematic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Minigames", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Satire", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Games Workshop", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Parody", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Trading Card Game", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Nonlinear", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Noir", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Gun Customization", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Grid-Based Movement", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Philosophical", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Crowdfunded", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "God Game", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Western", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Hex Grid", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Silent Protagonist", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Mythology", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Agriculture", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Deckbuilding", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Assassin", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Card Battler", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Time Travel", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Bullet Time", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Cats", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "TrackIR", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Hunting", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Time Attack", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Gothic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Gaming", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Dog", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Villain Protagonist", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "America", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Tabletop", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Underwater", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Trading", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Investigation", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "FMV", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Class-Based", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Football", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Precision Platformer", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Heist", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Soccer", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Martial Arts", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Programming", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Fishing", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Quick-Time Events", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Vampire", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Combat", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Farming Sim", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "World War I", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Spectacle fighter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Colony Sim", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Word Game", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Time Manipulation", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Artificial Intelligence", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Dynamic Narration", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Immersive Sim", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Based On A Novel", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Mining", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Conspiracy", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Capitalism", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Sequel", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Mystery Dungeon", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Naval Combat", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Sniper", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Unforgiving", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Faith", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Asynchronous Multiplayer", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Music-Based Procedural Generation", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Chess", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Horses", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "360 Video", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Political Sim", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Offroad", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Sailing", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Warhammer 40K", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Life Sim", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Pinball", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "LEGO", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "6DOF", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Diplomacy", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Gambling", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Conversation", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "On-Rails Shooter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Mars", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Star Wars", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Typing", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Sokoban", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Trivia", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Underground", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Automation", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Rome", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Golf", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Intentionally Awkward Controls", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Vehicular Combat", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Steam Machine", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Werewolves", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Motorbike", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Traditional Roguelike", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Transportation", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Solitaire", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Basketball", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Combat Racing", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Batman", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Benchmark", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "3D Fighter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Mini Golf", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Hero Shooter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Idler", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Transhumanism", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Bikes", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Hardware", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Medical Sim", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Boxing", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Wrestling", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Archery", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Feature Film", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Snow", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Baseball", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Looter Shooter", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Submarine", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Foreign", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Asymmetric VR", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Pool", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Cycling", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Collectathon", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Voice Control", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Tennis", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Bowling", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Roguevania", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Outbreak Sim", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Hockey", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Electronic Music", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Skateboarding", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Jet", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Ambient", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Motocross", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Lemmings", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Lara Croft", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Skating", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Spelling", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Social Deduction", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Auto Battler", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Instrumental Music", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Snowboarding", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "BMX", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Skiing", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Rock Music", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "ATV", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
  { tag: "Electronic", count: 0, reviewScore: 0, averagePrice: [], averageCcu: [] },
];

export default tags;
